gText_Birch_Welcome::
	.string "Welcome to the world of ironMON!\p"
	.string "$"

gText_Birch_Pokemon::
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "In fact, there are many, many\n"
	.string "secrets surrounding this challenge.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "And you are?$"

gText_Birch_BoyOrGirl::
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gText_Birch_WhatsYourName::
	.string "All right.\n"
	.string "What's your name?$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Ah, okay!\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "Good luck on your run!\p"
	.string "$"
