ViridianCity_House_Text_NicknamingIsFun::
    .string "Talk to my Birdge if you\n"
    .string "want to change nicknames.$"

ViridianCity_House_Text_MyDaddyLovesMonsToo::
    .string "Want to evolve your POKéMON?$"

ViridianCity_House_Text_EvoFailed::
    .string "I can't evolve that POKéMON!$"

ViridianCity_House_Text_EvoUnderleveled::
    .string "You need to be at least level 10!$"

ViridianCity_House_Text_Speary::
    .string "SPEARY: Tetweet!$"

ViridianCity_House_Text_SpearowNameSpeary::
    .string "SPEAROW\n"
    .string "Name: SPEARY$"

