name: CI

on:
  push:
    branches: [ firered ]

jobs:
  jar:
    uses: champred/UPR-Android/.github/workflows/jar.yml@master
  build:
    runs-on: ubuntu-latest
    env:
      GAME_VERSION: FIRERED
      GAME_LANGUAGE: ENGLISH
      GAME_REVISION: 1
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Checkout agbcc
        uses: actions/checkout@master
        with:
          path: 'agbcc'
          repository: 'pret/agbcc'

      - name: Checkout symbols
        if: ${{ github.event_name == 'push' }}
        uses: actions/checkout@master
        with:
          path: 'symbols'
          ref: 'fr-symbols'

      - name: Install binutils
        run: sudo apt install gcc-arm-none-eabi binutils-arm-none-eabi libcapstone-dev
        # build-essential, git, and libpng-dev are already installed
        # gcc-arm-none-eabi is only needed for the modern build
        # as an alternative to dkP

      - name: Install agbcc
        run: |
          ./build.sh
          ./install.sh ../
        working-directory: ./agbcc

      - name: Build ROM
        run: make -j${nproc} all syms

      - name: Move symfiles
        if: ${{ github.event_name == 'push' }}
        run: |
          cp *.sym symbols/
          echo "SYMBOLS_COMMIT_MSG=$( git log --format=%s ${GITHUB_SHA} )" >> $GITHUB_ENV

      - name: Update symfiles
        if: ${{ github.event_name == 'push' }}
        uses: EndBug/add-and-commit@v7
        with:
          branch: fr-symbols
          cwd: "./symbols"
          add: "*.sym"
          message: ${{ env.SYMBOLS_COMMIT_MSG }}

      - name: Download JAR
        uses: actions/download-artifact@v4
        with:
          name: JAR

      - name: Update JAR
        run: ./offgen.sh

      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: Updated JAR
          path: upr.jar
