name: CI

on:
  push:
    branches: [ phys-spec-split ]
  pull_request:

jobs:
  jar:
    uses: champred/UPR-Android/.github/workflows/jar.yml@master
  build:
    runs-on: ubuntu-latest
    env:
      GAME_VERSION: EMERALD
      GAME_REVISION: 0
      GAME_LANGUAGE: ENGLISH
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout syms
        if: ${{ github.event_name == 'push' }}
        uses: actions/checkout@v4
        with:
          path: symbols
          ref: symbols

      - name: Checkout agbcc
        uses: actions/checkout@v4
        with:
          path: agbcc
          repository: pret/agbcc

      - name: Install binutils
        run: sudo apt install gcc-arm-none-eabi binutils-arm-none-eabi libcapstone-dev

      - name: Install agbcc
        run: |
          ./build.sh
          ./install.sh ../
        working-directory: agbcc

      - name: Build ROM
        run: make -j${nproc} all syms

      - name: Move symfiles
        if: ${{ github.event_name == 'push' }}
        run: |
          cp -v *.sym symbols/
          echo "SYMBOLS_COMMIT_MSG=$( git log --format=%s ${GITHUB_SHA} )" >> $GITHUB_ENV

      - name: Update symfiles
        if: ${{ github.event_name == 'push' }}
        uses: EndBug/add-and-commit@v7
        with:
          branch: symbols
          cwd: "./symbols"
          add: "*.sym"
          message: ${{ env.SYMBOLS_COMMIT_MSG }}

      - name: Download JAR
        uses: actions/download-artifact@v4
        with:
          name: JAR

      - name: Generate Offsets
        run: ./offgen.sh

      - name: Upload Files
        uses: actions/upload-artifact@v4
        with:
          name: Dist
          path: dist
